### ISSUE TITLE
Scroll snapping

### ISSUE THREAD

**Issue by vovaguguiev** [vovaguguiev/FramerSunbeam#5]
@hellonicolas proposed the following feature:

> For the Scroll component, I'd love to have more control over the timing, animation, and final position when scrolling. For example, certain TV platforms tend to keep your focused items vertically centered, while others may choose to anchor towards the top or bottom of the screen. Happy to provide screen captures if that doesn't make sense.

> I meant having more granular control of where the Scroll container scrolls to. For example, if I have a top navigation bar and focus there, I want `Scroll` to always snap to the top. Or, in a certain layout if I focus on a specific row, I want Scroll to snap to a very specific point. It's kind of weird to describe, but "scroll snapping" is something we had to consider a lot in our TV apps because the auto-scrolling mechanism didn't result in a perfect scrolling experience 100% of the time.

@hellonicolas could you, please, provide the screen captures you mentioned? It will tremendously help to implement this feature.

**Comment by hellonicolas** [comment]
@vovaguguiev Sorry for the delay!

Here's a really specific example where it's been helpful to have control over when / where Scroll moves:
![](https://thumbs.gfycat.com/BigheartedRightAmericanwigeon-size_restricted.gif)

When the focus moves to **Season 1**, _technically_ it's in view so it wouldn't scroll the page on its own. However, wanted to force a scroll so that the first row of episodes is visible. Same idea when moving back to the big tile/image at the top of the page; we want that to scroll back up to the top when it's in focus. Basically some way to override / modify where Scroll goes to would help :)

Hopefully that makes sense; I can provide other examples if you need, LMK!

**Comment by phillamu** [comment]
After updating Framer to version 38, I cannot install Framer Sunbeam. Could this be a bug?

**Comment by vovaguguiev** [comment]
You now can control the scroll stickiness with `vertical_stickiness` and `horizontal_stickiness` props, see more: [here](https://github.com/vovaguguiev/FramerSunbeam/blob/master/README.md#-stickiness---vertical_stickiness-auto--top--bottom---default-auto)
